### ISSUE TITLE
autopipeline failure to save RTStruct due to name containing invalid character "<"

### ISSUE THREAD

**Issue by jpeoples** [bhklab/med-imagetools#45]
I ran the autopipeline again to process our RTSTRUCTs. This mostly works. There were a couple small issues.

The first is, as I said in the title, one of the RTStruct contours contains "<", which creates an error. I believe this is most likely because "<" is invalid in a Windows path.

The error text is simply

```
** ERROR (nifti_image_write_hdr_img2): cannot open output file 'liver_autopipe/0_20243743626/RTSTRUCT_CT/z_liver<1500.nii.gz'
```

The other errors were a couple warnings about being unable to get points for a few ROIs in one of the subjects, but I think they might just be empty.

**Comment by skim2257** [comment]
To implement file path checking with these invalid characters: https://stackoverflow.com/a/31976060/15664287

**Comment by skim2257** [comment]
Resolved  with commit.
