### ISSUE TITLE
How can I ignore files/subjects with error?

### ISSUE THREAD

**Issue by SWKoreaBME** [bhklab/med-imagetools#75]
Hi, 

I tried using med-imagetools to process the [dataset](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70229053#70229053daab16fd800d4209912f3979a478fe76).

But I got an error and it stopped. Is there any way to ignore the files with an error and make it keep processing?

Just in case the error message is:

```
Traceback (most recent call last):
  File "/cluster/home/kimsa/anaconda3/envs/torch38/lib/python3.8/site-packages/imgtools/modules/structureset.py", line 114, in get_mask
    mask[z, :, :, idx] += slice_mask
IndexError: index 119 is out of bounds for axis 0 with size 119
```

Thank you!

**Comment by skim2257** [comment]
it seems like the image-mask geometry is slightly offset and the slice you're looking to add is just outside of the size of the image. 
try using the `--warn_on_error` flag to skip bad samples.
